// qFoldIT Toolbelt for Unity — ToolbeltRegistry.cs
//
// Every [McpTool]-decorated method in Editor/Tools/*.cs is discovered
// automatically by Unity's own McpToolRegistry (TypeCache scan at editor
// startup) — that part is handled entirely by com.unity.ai.assistant.
//
// This class only adds a qFoldIT-specific convenience layer on top:
//   1. A single source of truth for "what tool categories exist" so the
//      dashboard window and the exported manifest stay in sync.
//   2. tool_manifest.json export — same idea as UEFN Toolbelt's
//      plugin_export_manifest, so an AI agent (or a human) can load one
//      file and know every tool's name, category and description without
//      reading source.
//
// This file intentionally does NOT re-implement tool discovery: Unity MCP
// already reflects over assemblies via TypeCache, so duplicating that here
// would just be a second, driftable source of truth.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace QFoldIT.Toolbelt.Editor.Core
{
    /// <summary>
    /// Static description of a qFoldIT Toolbelt tool category, used only for
    /// the dashboard UI and the exported manifest — not for dispatch.
    /// </summary>
    public readonly struct ToolbeltCategory
    {
        public readonly string Name;
        public readonly string Description;

        public ToolbeltCategory(string name, string description)
        {
            Name = name;
            Description = description;
        }
    }

    public static class ToolbeltRegistry
    {
        public const string ToolbeltVersion = "0.1.0";
        public const string Organization = "qFoldIT";

        public static readonly ToolbeltCategory[] Categories =
        {
            new ToolbeltCategory("Scene",       "Spawn, transform, clone, parent, and query GameObjects in the open scene."),
            new ToolbeltCategory("Materials",   "Material presets, bulk swap, team-color split, procedural material generation."),
            new ToolbeltCategory("Procedural",  "Geometric placement patterns: grid, circle, arc, spiral, line, wave, helix, radial."),
            new ToolbeltCategory("Arena",       "Symmetrical competitive layout generator with team-color auto split."),
            new ToolbeltCategory("Stamps",      "Save a selection of objects as a reusable stamp; place it anywhere later."),
            new ToolbeltCategory("Project",     "Scaffold folder structure and boilerplate scripts for a new project."),
            new ToolbeltCategory("WorldState",  "Export the live scene graph to JSON so an AI agent has full context."),
            new ToolbeltCategory("CodeGen",     "Generate wired MonoBehaviour boilerplate referencing real scene objects."),
            new ToolbeltCategory("Assets",      "Query, import, and instantiate project assets and prefabs."),
            new ToolbeltCategory("BuildConsole","Trigger builds, run editor commands, read the console log."),
        };

        /// <summary>
        /// Writes Saved-equivalent manifest describing every category. Full
        /// per-tool schema (name/description/params) is already generated by
        /// Unity MCP itself via reflection; we surface it alongside our own
        /// category metadata for a single combined manifest file.
        /// </summary>
        [MenuItem("qFoldIT/Toolbelt/Export Tool Manifest")]
        public static void ExportManifest()
        {
            var manifest = new ManifestRoot
            {
                organization = Organization,
                toolbelt = "unity",
                version = ToolbeltVersion,
                generated = DateTime.UtcNow.ToString("yyyy-MM-dd"),
                categories = Categories.Select(c => new ManifestCategory
                {
                    name = c.Name,
                    description = c.Description
                }).ToList()
            };

            string dir = Path.Combine(Application.dataPath, "..", "Saved", "QFoldIT_Toolbelt");
            Directory.CreateDirectory(dir);
            string path = Path.Combine(dir, "tool_manifest.json");
            File.WriteAllText(path, JsonUtility.ToJson(manifest, true));

            Debug.Log($"[qFoldIT Toolbelt] Manifest written to {path}. " +
                      "Per-tool schemas are available live from any connected MCP client " +
                      "via the standard MCP 'list tools' call — Unity MCP generates those " +
                      "automatically from the [McpTool]/[McpDescription] attributes.");
        }

        [Serializable]
        private class ManifestRoot
        {
            public string organization;
            public string toolbelt;
            public string version;
            public string generated;
            public List<ManifestCategory> categories;
        }

        [Serializable]
        private class ManifestCategory
        {
            public string name;
            public string description;
        }
    }
}
