// qFoldIT Toolbelt for Unity — CodeGenTools.cs
// Category: CodeGen
// Generates a MonoBehaviour skeleton with a public field for every named
// scene object requested, so the AI-authored gameplay code has real,
// bindable references instead of magic strings. Mirrors UEFN Toolbelt's
// Verse code generation step that reads world_state.json and wires @editable
// device references automatically.

using System.IO;
using System.Linq;
using System.Text;
using Unity.AI.MCP.Editor.ToolRegistry;
using UnityEditor;
using UnityEngine;

namespace QFoldIT.Toolbelt.Editor.Tools
{
    public static class CodeGenTools
    {
        public class CodegenMonoBehaviourParams
        {
            [McpDescription("Class name for the generated MonoBehaviour", Required = true)]
            public string ClassName { get; set; }

            [McpDescription("Comma-separated GameObject names in the scene to expose as public fields", Required = true)]
            public string ObjectNames { get; set; }

            [McpDescription("Output path relative to Assets/, e.g. Scripts/Gameplay/RoundController.cs", Required = true)]
            public string OutputPath { get; set; }

            [McpDescription("C# namespace to wrap the class in", Default = "")]
            public string Namespace { get; set; } = "";
        }

        [McpTool("codegen_monobehaviour", "Generates a MonoBehaviour with a public serialized field for each named scene object, plus empty lifecycle methods — a wired starting point rather than magic-string lookups at runtime.")]
        public static object CodegenMonoBehaviour(CodegenMonoBehaviourParams p)
        {
            var names = p.ObjectNames.Split(',').Select(n => n.Trim()).Where(n => n.Length > 0).ToList();
            var missing = names.Where(n => GameObject.Find(n) == null).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// Generated by qFoldIT Toolbelt — codegen_monobehaviour");
            sb.AppendLine("// Drag the referenced objects from the Hierarchy into the Inspector slots below.");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();

            bool hasNs = !string.IsNullOrEmpty(p.Namespace);
            if (hasNs) { sb.AppendLine($"namespace {p.Namespace}"); sb.AppendLine("{"); }

            sb.AppendLine($"    public class {p.ClassName} : MonoBehaviour");
            sb.AppendLine("    {");
            foreach (var n in names)
            {
                var fieldName = char.ToLowerInvariant(n[0]) + SanitizeIdentifier(n).Substring(1);
                sb.AppendLine($"        [SerializeField, Tooltip(\"Scene object: {n}\")]");
                sb.AppendLine($"        private GameObject {fieldName};");
            }
            sb.AppendLine();
            sb.AppendLine("        private void Awake() { }");
            sb.AppendLine();
            sb.AppendLine("        private void Start() { }");
            sb.AppendLine("    }");
            if (hasNs) sb.AppendLine("}");

            var fullPath = Path.Combine(Application.dataPath, p.OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath) ?? ".");
            File.WriteAllText(fullPath, sb.ToString());
            AssetDatabase.Refresh();

            return new
            {
                success = true,
                class_name = p.ClassName,
                path = $"Assets/{p.OutputPath}",
                fields_generated = names.Count,
                objects_not_found_in_scene = missing
            };
        }

        private static string SanitizeIdentifier(string raw)
        {
            var clean = new string(raw.Where(char.IsLetterOrDigit).ToArray());
            return string.IsNullOrEmpty(clean) ? "field" : clean;
        }
    }
}
