// qFoldIT Toolbelt for Unity — ProjectSetupTools.cs
// Category: Project
// Mirrors UEFN Toolbelt's project_setup: a standard folder skeleton plus a
// boilerplate GameManager MonoBehaviour, generated in one call.

using System.IO;
using System.Linq;
using Unity.AI.MCP.Editor.ToolRegistry;
using UnityEditor;
using UnityEngine;

namespace QFoldIT.Toolbelt.Editor.Tools
{
    public static class ProjectSetupTools
    {
        private static readonly string[] StandardFolders =
        {
            "Scripts", "Scripts/Gameplay", "Scripts/UI", "Scripts/Managers",
            "Prefabs", "Prefabs/Environment", "Prefabs/Characters", "Prefabs/Props",
            "Materials", "Textures", "Models", "Audio", "Audio/Music", "Audio/SFX",
            "Scenes", "ScriptableObjects", "Animations", "Editor"
        };

        public class ProjectSetupParams
        {
            [McpDescription("Root name for the project, used for the generated GameManager class", Required = true)]
            public string ProjectName { get; set; }
        }

        [McpTool("project_setup", "Creates a standard folder structure under Assets/<ProjectName> and generates a boilerplate <ProjectName>GameManager MonoBehaviour singleton.")]
        public static object ProjectSetup(ProjectSetupParams p)
        {
            var safeName = SanitizeName(p.ProjectName);
            var root = Path.Combine("Assets", safeName);
            int foldersCreated = 0;

            foreach (var folder in StandardFolders)
            {
                var full = Path.Combine(root, folder);
                if (!AssetDatabase.IsValidFolder(full))
                {
                    CreateFolderRecursive(full);
                    foldersCreated++;
                }
            }

            var scriptDir = Path.Combine(Application.dataPath, safeName, "Scripts", "Managers");
            Directory.CreateDirectory(scriptDir);
            var scriptPath = Path.Combine(scriptDir, $"{safeName}GameManager.cs");
            File.WriteAllText(scriptPath, GenerateGameManagerSource(safeName));

            AssetDatabase.Refresh();

            return new
            {
                success = true,
                project_name = safeName,
                folders_created = foldersCreated,
                script_generated = $"Assets/{safeName}/Scripts/Managers/{safeName}GameManager.cs"
            };
        }

        private static string SanitizeName(string name)
        {
            var clean = new string(name.Where(char.IsLetterOrDigit).ToArray());
            return string.IsNullOrEmpty(clean) ? "MyGame" : clean;
        }

        private static void CreateFolderRecursive(string assetPath)
        {
            var parts = assetPath.Split('/');
            var current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {
                var next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }

        private static string GenerateGameManagerSource(string projectName) =>
$@"// Generated by qFoldIT Toolbelt — project_setup
using UnityEngine;

namespace {projectName}
{{
    /// <summary>
    /// Boilerplate singleton game manager. Wire round flow, scoring, and
    /// win conditions here — generated as a starting point, not a final
    /// implementation.
    /// </summary>
    public class {projectName}GameManager : MonoBehaviour
    {{
        public static {projectName}GameManager Instance {{ get; private set; }}

        private void Awake()
        {{
            if (Instance != null && Instance != this) {{ Destroy(gameObject); return; }}
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }}

        private void Start()
        {{
            Debug.Log(""[{projectName}GameManager] Initialized."");
        }}
    }}
}}
";
    }
}
